base_frame: base_link
fixed_frame: odom

publish_tf: true
publish_odom: true

use_odom: false
use_imu: false

max_iterations: 10
max_correspondence_dist: 0.5
max_angular_correction_deg: 45.0
max_linear_correction: 0.5
epsilon_xy: 0.000001
epsilon_theta: 0.000001
outliers_maxPerc: 0.9
