# Kobuki approximate square footprint (0.36m × 0.36m)
footprint: [ [-0.18,-0.18], [0.18,-0.18], [0.18,0.18], [-0.18,0.18] ]

transform_tolerance: 0.5
map_type: costmap

obstacle_layer:
  enabled: true
  obstacle_range: 5.0
  raytrace_range: 5.5
  track_unknown_space: false
  combination_method: 1
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true

inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0
  inflation_radius: 0.22

static_layer:
  enabled: true
  map_topic: "/map"
